### ISSUE TITLE
msm install error

### ISSUE THREAD

**Issue by adamc199** [joshuacox/skill-na-show#1]
Installed with msm, upon loading the following error appeared in the log:

```
14:39:44.819 - mycroft.skills.core:load_skill:144 - ERROR - Failed to load skill: skill-na-show.joshuacox
Traceback (most recent call last):
File "/home/pi/mycroft-core/mycroft/skills/core.py", line 115, in load_skill
('.py', 'rb', imp.PY_SOURCE)
File "/usr/lib/python3.5/imp.py", line 234, in load_module
return load_source(name, filename, file)
File "/usr/lib/python3.5/imp.py", line 172, in load_source
module = _load(spec)
File "<frozen importlib._bootstrap>", line 693, in _load
File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 669, in exec_module
File "<frozen importlib._bootstrap_external>", line 775, in get_code
File "<frozen importlib._bootstrap_external>", line 735, in source_to_code
File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
File "/opt/mycroft/skills/skill-na-show.joshuacox/__init__.py", line 67
url = data.enclosures[0]['url'])
^
SyntaxError: invalid syntax
```

TYFYC!

**Comment by joshuacox** [comment]
`git pull`  there was an errant ')' parens at that point.  Should be fixed now.  Thanks for trying it out!  And even more thanks for the best podcast in the universe!

**Comment by adamc199** [comment]
Install successful
Recognized 
"In the morning"
Heard voice say: "straight from gitmo nation"

Then an error occurred:

```
16:13:27.227 - skill-na-show_joshuacox:handle_intent:68 - INFO - https://mp3s.nashownotes.com/NA-1043-2018-06-17-Final.mp3
16:13:27.230 - skill-na-show_joshuacox:handle_intent:73 - INFO - AudioService

Traceback (most recent call last):
File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 141, in _new_conn
(self.host, self.port), self.timeout, **extra_kw)
File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 83, in create_connection
raise err
File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 73, in create_connection
sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
chunked=chunked)
File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
self._validate_conn(conn)
File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
conn.connect()
File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 284, in connect
conn = self._new_conn()
File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 146, in _new_conn
(self.host, self.timeout))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
timeout=timeout
File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
_stacktrace=sys.exc_info()[2])
File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 376, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/pi/mycroft-core/mycroft/skills/settings.py", line 396, in _poll_skill_settings
self.update_remote()
File "/home/pi/mycroft-core/mycroft/skills/settings.py", line 371, in update_remote
skills_settings = self._request_other_settings(hashed_meta)
File "/home/pi/mycroft-core/mycroft/skills/settings.py", line 479, in _request_other_settings
"path": path
File "/home/pi/mycroft-core/mycroft/api/__init__.py", line 62, in request
return self.send(params)
File "/home/pi/mycroft-core/mycroft/api/__init__.py", line 108, in send
data=data, json=json_body, timeout=(3.05, 15)
File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/api.py", line 56, in request
return session.request(method=method, url=url, **kwargs)
File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
resp = self.send(prep, **send_kwargs)
File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
r = adapter.send(request, **kwargs)
File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/adapters.py", line 479, in send
raise ConnectTimeout(e, request=request)
  ^--- NEWEST ---^ 
```

**Comment by joshuacox** [comment]
I can see that it is still using an out of date version as the info log reads:
```
INFO - https://mp3s.nashownotes.com/
```
I got the python feed parse to correct that at some point.

Just getting around to learning how `msm` works, you should be able to 
```
msm update
```
 and it will update to the latest version, on mine currently I show this commit:

```
commit 6414a069c1ac60ff98c426518a43d95072d0baf6
Author: Josh Cox <josh@webhosting.coop>
Date:   Mon Jun 18 18:03:08 2018 -0500

    Wait working properly again
```

from this dir:
```
$ pwd
/opt/mycroft/skills/skill-na-show
```

EDIT: updating commit id

**Comment by joshuacox** [comment]
Added a bunch of updates today:

```
git log -n1 |cat
commit 31a847708e03567dc02ac9d59f6f5d00b86835fc
Author: Josh Cox <josh@webhosting.coop>
Date:   Tue Jun 19 11:56:54 2018 -0500

    Added who as query and updated readme
```

improved the overall recognition, and added a random and up to 15th selector (that seems to be the limit on the RSS feed). 

 `msm update` ought to pull them all down, let me know if you have another git commit checked out into `/opt/mycroft/skills/skill-na-show`

**Comment by joshuacox** [comment]
perhaps msm needs to be aliased to m5m?

add this to bashrc:
```
alias m5m="msm"
```

then `source ~/.bashrc`

now `m5m update`  should do the updates ;)
